### ISSUE TITLE
Empty LINK attribute causes exception on class instance creation

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#444]
1. Create ClassA with linkProperty (type=LINK) attribute 
2. Do not select linked class
3. Save attribute
4. Go to Show Documents of ClassA
5. Press [Create] to create an instance of a class

ER: Warning "Cannot create an instance of the class <currentClassName>. There is no linked class in <attributeName> with type <attributeType>, please configure <URLToProperty>"

AR: Exception

```java
Unexpected RuntimeException

Last cause: null
WicketMessage: Error attaching this container for rendering: [ListView [Component id = rows]]

Stacktrace

Root cause:

java.lang.NullPointerException
     at org.orienteer.core.component.visualizer.ListboxVisualizer.createComponent(ListboxVisualizer.java:44)
     at org.orienteer.core.component.meta.ODocumentMetaPanel.resolveComponent(ODocumentMetaPanel.java:104)
     at org.orienteer.core.component.meta.ODocumentMetaPanel.resolveComponent(ODocumentMetaPanel.java:45)
     at org.orienteer.core.component.meta.AbstractModeMetaPanel.resolveComponent(AbstractModeMetaPanel.java:53)
     at org.orienteer.core.component.meta.AbstractMetaPanel.onConfigure(AbstractMetaPanel.java:75)
     at org.apache.wicket.Component.configure(Component.java:1055)
     at ru.ydn.wicket.wicketorientdb.behavior.SyncVisibilityBehaviour.onConfigure(SyncVisibilityBehaviour.java:22)
     at org.apache.wicket.Component.configure(Component.java:1060)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:940)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:143)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.markup.html.form.Form.onBeforeRender(Form.java:1807)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:143)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.extensions.markup.html.tabs.TabbedPanel.onBeforeRender(TabbedPanel.java:274)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Page.onBeforeRender(Page.java:801)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.Component.internalPrepareForRender(Component.java:2215)
     at org.apache.wicket.Page.internalPrepareForRender(Page.java:242)
     at org.apache.wicket.Component.render(Component.java:2304)
     at org.apache.wicket.Page.renderPage(Page.java:1018)
     at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
     at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
     at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
     at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
     at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
     at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
     at org.eclipse.jetty.server.Server.handle(Server.java:499)
     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
     at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
     at java.lang.Thread.run(Thread.java:745)

Complete stack:

org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [ListView [Component id = rows]]
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1843)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:143)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.markup.html.form.Form.onBeforeRender(Form.java:1807)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:143)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.extensions.markup.html.tabs.TabbedPanel.onBeforeRender(TabbedPanel.java:274)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1831)
     at org.apache.wicket.Component.onBeforeRender(Component.java:3879)
     at org.apache.wicket.Page.onBeforeRender(Page.java:801)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
     at org.apache.wicket.Component.internalPrepareForRender(Component.java:2215)
     at org.apache.wicket.Page.internalPrepareForRender(Page.java:242)
     at org.apache.wicket.Component.render(Component.java:2304)
     at org.apache.wicket.Page.renderPage(Page.java:1018)
     at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)

display page view
```

**Comment by PhantomYdn** [comment]
Fixed in mentioned above commit
