### ISSUE TITLE
NPE during selection of document to reference to

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/Orienteer#790]
```
java.lang.NullPointerException
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:125)
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:82)
     at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.execute(OLevelZeroIdentifier.java:52)
     at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:62)
     at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:111)
     at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
     at com.orientechnologies.orient.core.sql.parser.OContainsTextCondition.evaluate(OContainsTextCondition.java:42)
     at com.orientechnologies.orient.core.sql.parser.ONotBlock.evaluate(ONotBlock.java:44)
     at com.orientechnologies.orient.core.sql.parser.OAndBlock.evaluate(OAndBlock.java:47)
     at com.orientechnologies.orient.core.sql.parser.OOrBlock.evaluate(OOrBlock.java:49)
     at com.orientechnologies.orient.core.sql.parser.OWhereClause.matchesFilters(OWhereClause.java:56)
     at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:64)
     at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
     at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.executeAggregation(AggregateProjectionCalculationStep.java:91)
     at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.syncPull(AggregateProjectionCalculationStep.java:43)
     at com.orientechnologies.orient.core.sql.executor.GuaranteeEmptyCountStep.syncPull(GuaranteeEmptyCountStep.java:25)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
     at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
     at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
     at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
     at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:296)
     at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:81)
     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.query(ODatabaseDocumentEmbedded.java:573)
     at ru.ydn.wicket.wicketorientdb.model.OQueryModel.size(OQueryModel.java:243)
     at ru.ydn.wicket.wicketorientdb.model.OQueryDataProvider.size(OQueryDataProvider.java:107)
```

**Comment by PhantomYdn** [comment]
Depends on https://github.com/orientechnologies/orientdb/issues/9405

**Comment by PhantomYdn** [comment]
NPE was fixed, but there are related issue with containstext https://github.com/orientechnologies/orientdb/issues/9474
