### ISSUE TITLE
Can't dynamically load Tours due to exception

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/Orienteer#805]
```
newdemo      | java.lang.NoSuchFieldError: INCLUDE_ALL
newdemo      |  at org.glassfish.jersey.server.ResourceConfig$State.<init>(ResourceConfig.java:93)
newdemo      |  at org.glassfish.jersey.server.ResourceConfig.<init>(ResourceConfig.java:331)
newdemo      |  at org.orienteer.wicketjersey.WicketJersey$1.<init>(WicketJersey.java:39)
newdemo      |  at org.orienteer.wicketjersey.WicketJersey.mount(WicketJersey.java:39)
newdemo      |  at org.orienteer.tours.OToursModule.onInitialize(OToursModule.java:81)
newdemo      |  at org.orienteer.core.module.AbstractOrienteerModule.onInitialize(AbstractOrienteerModule.java:83)
newdemo      |  at org.orienteer.core.module.ModuledDataInstallator.loadOrienteerModules(ModuledDataInstallator.java:120)
newdemo      |  at org.orienteer.core.module.ModuledDataInstallator.installData(ModuledDataInstallator.java:73)
newdemo      |  at ru.ydn.wicket.wicketorientdb.AbstractDataInstallator.onAfterInitialized(AbstractDataInstallator.java:26)
newdemo      |  at org.apache.wicket.ApplicationListenerCollection$1.notify(ApplicationListenerCollection.java:39)
newdemo      |  at org.apache.wicket.ApplicationListenerCollection$1.notify(ApplicationListenerCollection.java:35)
newdemo      |  at org.apache.wicket.util.listener.ListenerCollection.notify(ListenerCollection.java:80)
newdemo      |  at org.apache.wicket.ApplicationListenerCollection.onAfterInitialized(ApplicationListenerCollection.java:34)
newdemo      |  at org.apache.wicket.Application.initApplication(Application.java:784)
newdemo      |  at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:450)
newdemo      |  at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:374)
newdemo      |  at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:110)
newdemo      |  at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:98)
newdemo      |  at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:232)

```

**Comment by PhantomYdn** [comment]
Inderectly fixed by c6047624207e575f7d7519a8937523b36c3e2682

The distributed mode should be reimplemented
